"""esquema inicial: leads, conversas, unidades

Revision ID: 24ea6deee20e
Revises:
Create Date: 2026-09-04 22:58:47.668050
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "24ea6deee20e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nome_cifrado", sa.LargeBinary(), nullable=False),
        sa.Column("telefone_cifrado", sa.LargeBinary(), nullable=False),
        sa.Column("telefone_hash", sa.String(length=64), nullable=False),
        sa.Column("origem", sa.String(length=32), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ultimo_acesso_em", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leads_telefone_hash"), "leads", ["telefone_hash"], unique=True)
    op.create_table(
        "unidades",
        sa.Column("chassi", sa.String(length=17), nullable=False),
        sa.Column("marca", sa.String(length=40), nullable=False),
        sa.Column("modelo", sa.String(length=60), nullable=False),
        sa.Column("versao", sa.String(length=60), nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("cor", sa.String(length=30), nullable=False),
        sa.Column("condicao", sa.String(length=10), nullable=False),
        sa.Column("km", sa.Integer(), nullable=False),
        sa.Column("preco_centavos", sa.BigInteger(), nullable=False),
        sa.Column("autonomia_km", sa.Integer(), nullable=True),
        sa.Column("autonomia_fonte", sa.String(length=30), nullable=True),
        sa.Column("foto_url", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=14), nullable=False),
        sa.Column("reservado_para", sa.Uuid(), nullable=True),
        sa.Column("reservado_em", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("condicao IN ('novo', 'seminovo')", name="ck_unidades_condicao"),
        sa.CheckConstraint(
            "status IN ('disponivel', 'reservado', 'vendido', 'indisponivel')",
            name="ck_unidades_status",
        ),
        sa.CheckConstraint(
            "(autonomia_km IS NULL) = (autonomia_fonte IS NULL)",
            name="ck_unidades_autonomia_sempre_com_fonte",
        ),
        sa.CheckConstraint("preco_centavos > 0", name="ck_unidades_preco_positivo"),
        sa.PrimaryKeyConstraint("chassi"),
    )
    op.create_index(op.f("ix_unidades_status"), "unidades", ["status"], unique=False)
    op.create_table(
        "conversas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("etapa", sa.String(length=24), nullable=False),
        sa.Column("canal_atual", sa.String(length=10), nullable=False),
        sa.Column("modo", sa.String(length=10), nullable=False),
        sa.Column("atendente_id", sa.Uuid(), nullable=True),
        sa.Column("qualificacao", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("chassi_em_foco", sa.String(length=17), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("token_sessao", sa.String(length=64), nullable=False),
        sa.Column("token_expira_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("criada_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ultima_mensagem_em", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("canal_atual IN ('web', 'whatsapp')", name="ck_conversas_canal"),
        sa.CheckConstraint(
            "etapa IN ('saudacao', 'qualificacao', 'recomendacao', 'objecao', 'condicao', 'aguardando_aprovacao', 'reserva', 'test_drive', 'humano', 'encerrada')",
            name="ck_conversas_etapa",
        ),
        sa.CheckConstraint("modo IN ('aurora', 'humano')", name="ck_conversas_modo"),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversas_token_sessao"), "conversas", ["token_sessao"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversas_token_sessao"), table_name="conversas")
    op.drop_table("conversas")
    op.drop_index(op.f("ix_unidades_status"), table_name="unidades")
    op.drop_table("unidades")
    op.drop_index(op.f("ix_leads_telefone_hash"), table_name="leads")
    op.drop_table("leads")
    # ### end Alembic commands ###
