"""S-07: vendedores, bloqueios de agenda e test drives

Os dois `EXCLUDE ... USING gist` de `test_drives` são o coração da S-07 §1: um proíbe
sobreposição para o mesmo vendedor, o outro para o mesmo chassi. Sem eles, "conferir e
depois gravar" deixa a mesma janela de corrida que a S-05 fecha na reserva — e o cliente
chega na loja para um carro que já saiu com outro.

`status <> 'cancelado'` no `WHERE` é o que faz desmarcar devolver a vaga.

Revision ID: 41b578425ada
Revises: 679a20ca920b
Create Date: 2026-09-05 20:56:40.570033
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '41b578425ada'
down_revision: str | None = '679a20ca920b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # gist sobre uuid exige btree_gist; sem esta linha o EXCLUDE abaixo não cria.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.create_table('vendedores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('telefone_cifrado', sa.LargeBinary(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('agenda_bloqueios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendedor_id', sa.Uuid(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_bloqueios_vendedor_id'), 'agenda_bloqueios', ['vendedor_id'], unique=False)
    op.create_table('test_drives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversa_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('chassi', sa.String(length=17), nullable=False),
    sa.Column('vendedor_id', sa.Uuid(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmado_em', sa.DateTime(timezone=True), nullable=True),
    postgresql.ExcludeConstraint((sa.literal_column('chassi'), '='), (sa.literal_column('tstzrange(inicio, fim)'), '&&'), where=sa.text("status <> 'cancelado'"), using='gist', name='ex_test_drives_chassi'),
    postgresql.ExcludeConstraint((sa.literal_column('vendedor_id'), '='), (sa.literal_column('tstzrange(inicio, fim)'), '&&'), where=sa.text("status <> 'cancelado'"), using='gist', name='ex_test_drives_vendedor'),
    sa.CheckConstraint("status IN ('agendado', 'confirmado', 'realizado', 'nao_compareceu', 'cancelado')", name='ck_test_drives_status'),
    sa.CheckConstraint('fim > inicio', name='ck_test_drives_intervalo_positivo'),
    sa.ForeignKeyConstraint(['chassi'], ['unidades.chassi'], ),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_drives_inicio'), 'test_drives', ['inicio'], unique=False)
    op.add_column('conversas', sa.Column('desfecho', sa.String(length=30), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversas', 'desfecho')
    op.drop_index(op.f('ix_test_drives_inicio'), table_name='test_drives')
    op.drop_table('test_drives')
    op.drop_index(op.f('ix_agenda_bloqueios_vendedor_id'), table_name='agenda_bloqueios')
    op.drop_table('agenda_bloqueios')
    op.drop_table('vendedores')
    # A extensão fica: outra coisa no banco pode estar usando.
