"""mensagens: o historico que atravessa os dois canais

`canal` é coluna da mensagem, não da conversa (S-02 §1): é o que faz o handoff do
ADR-005 manter id, histórico e qualificação ao trocar de web para WhatsApp.

`processada_em` é a fila de turnos. O CHECK `ck_mensagens_saida_nunca_pendente` fecha o
único estado sem sentido — resposta da Aurora esperando resposta da Aurora.

Revision ID: 679a20ca920b
Revises: 620bf4bce266
Create Date: 2026-09-05 16:56:12.040200
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '679a20ca920b'
down_revision: str | None = '620bf4bce266'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversa_id', sa.Uuid(), nullable=False),
    sa.Column('direcao', sa.String(length=8), nullable=False),
    sa.Column('autor', sa.String(length=10), nullable=False),
    sa.Column('canal', sa.String(length=10), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('gerada_por_ia', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_message_id', sa.String(length=64), nullable=True),
    sa.Column('payload_bruto', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processada_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("autor IN ('cliente', 'aurora', 'vendedor')", name='ck_mensagens_autor'),
    sa.CheckConstraint("canal IN ('web', 'whatsapp')", name='ck_mensagens_canal'),
    sa.CheckConstraint("direcao = 'entrada' OR processada_em IS NOT NULL", name='ck_mensagens_saida_nunca_pendente'),
    sa.CheckConstraint("direcao IN ('entrada', 'saida')", name='ck_mensagens_direcao'),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mensagens_conversa_criada', 'mensagens', ['conversa_id', 'criada_em'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mensagens_conversa_criada', table_name='mensagens')
    op.drop_table('mensagens')
    # ### end Alembic commands ###
